name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --dev
      - name: Run gts
        run: yarn lint
